services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - default
      - sonarnet
    ports:
      - "8080:8080"
      - "50000:50000"
  pg-tasks:
    image: postgres:9
    container_name: pg-tasks
    environment:
      POSTGRES_DB: tasks
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  tasks-app:
    depends_on:
      - pg-tasks
    build: .
    ports:
      - "8001:8001"
  sonarqube:
    container_name: sonar
    build: ./sonar-conf
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    depends_on:
      - pg-sonar
    environment:
      sonar.jdbc.url: jdbc:postgresql://pg-sonar/sonar
      sonar.jdbc.username: sonar
      sonar.jdbc.password: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
  pg-sonar:
    container_name: pg-sonar
    image: postgres:9.6
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - sonarqube_pg_data:/var/lib/postgresql/data

networks:
  sonarnet:

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_pg_data:
